version: '3'
services:
  web:
    build:
      context: ./html
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=db_first
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Test123
#    volumes:
#      - ./html:/var/www/html
#      - db_data:/var/lib/mysql
    depends_on:
      - db
    networks:
      - custom_network
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: db_first
      MYSQL_USER: user
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: Test123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - custom_network

volumes:
  db_data: {}

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
